### ISSUE TITLE
DNXCore support

### ISSUE THREAD

**Issue by IlyaKhD** [moq/moq#18] opened 2015-11-12 11:18 UTC
Do you have any milestones?

**Comment by maartenmensink** [comment] 2016-02-10 06:01
Would love to see dnxcore50 being supported!

**Comment by maartenmensink** [comment] 2016-02-10 06:06
I noticed microsoft guys have forked moq4 repo https://github.com/aspnet/moq4/commits/netcore

**Comment by justinhhorner** [comment] 2016-03-11 18:50
@maartenmensink Thanks for sharing that info. Were you able to get the solution working? I've tried in my dnxcore50 project but it fails to resolve it.

**Comment by maartenmensink** [comment] 2016-03-23 08:02
@justinhhorner yes i got it working. I just tried a new project and noticed it was moved to a other nuget repo. This should do the trick

nuget feed
`<add key="AspetC Contrib" value="https://www.myget.org/F/aspnet-contrib/api/v3/index.json" />`

project.json
```
{
  "version": "1.0.0-*",
  "description": "Moq.Test.Tests Console Application",
  "authors": [ "maartenmensink" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "NUnit": "3.2.0",
    "NUnitLite": "3.2.0",
    "FluentAssertions": "4.2.2",
    "AutoMapper": "4.2.1"
  },

  "commands": {
    "test": "Machine.Tests"
  },

  "frameworks": {
    "dnxcore50": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Console": "4.0.0-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Threading": "4.0.11-beta-23516",
        "moq.netcore": "4.4.0-beta8"
      }
    }
  }
}
```

Program.cs
```
using System;
using System.Reflection;
using FluentAssertions;
using NUnit.Common;
using NUnit.Framework;
using NUnitLite;

namespace Machine.Tests
{
    public class Program
    {
        public static void Main(string[] args)
        {
            new AutoRun(typeof(Program).GetTypeInfo().Assembly).Execute(args, new ExtendedTextWrapper(Console.Out), Console.In);
        }
    }

    [TestFixture]
    public class AwesomeTest
    {
        [Test]
        public void TrueShouldBeTrue()
        {
            true.Should().BeTrue();
        }
    }
}
```

**Comment by paurail** [comment] 2016-06-23 11:10
:+1:

**Comment by kzu** [comment] 2016-07-14 16:44
Dupe of https://github.com/moq/moq4/pull/225

**Closed by kzu** 2016-07-14 16:44 UTC
