### ISSUE TITLE
.NET Core?

### ISSUE THREAD

**Issue by PivotalAnimal** [moq/moq#21] opened 2016-07-14 03:55 UTC
Is this project no longer? It seems outdated. Are there any plans to upgrade to project.json?

**Comment by kzu** [comment] 2016-07-14 16:42
Duplicate of https://github.com/moq/moq4/pull/225

**Closed by kzu** 2016-07-14 16:42 UTC

**Comment by kzu** [comment] 2016-07-14 16:44
BTW, project.json doesn't seem like it will have a long life, so we may never "upgrade" to it. 

See https://github.com/Microsoft/msbuild/issues?q=is%3Aissue+is%3Aopen+label%3AParity-XProj
